apiVersion: apps/v1
kind: Deployment
metadata:
  name: guidworker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guidworker
  template:
    metadata:
      labels:
        app: guidworker
    spec:
      containers:
        - image: oyvindss/guidworker:latest
          name: guidworker
          volumeMounts:
            - mountPath: /guids
              name: raw-data
      volumes:
        - name: raw-data
          persistentVolumeClaim:
            claimName: raw-data-pvc