apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: raw-data-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 5Gi
  selector:
    matchLabels:
        type: local