apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guid-data-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 5Gi
  selector:
    matchLabels:
        type: local